# fly.toml app configuration file generated for goalbot-bluesky-bot on 2024-12-09T23:18:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goalbot-bluesky-bot'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 3600
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[env]
  PORT = "3600"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


